### ISSUE TITLE
Mainhand and offhand reforge stats stack!

### ISSUE THREAD

**Issue by heybangsie** [Auxilor/Reforges#15]
**Describe the bug**
Mainhand and offhand reforge stats stack!

**Expected behavior**
Disable reforges in weapon when in offhand

**Server Information (please complete the following information):**
- Version: 1.18.1
- Version of plugin and eco (`/ver eco-6.24.2-all`, `/ver <Reforges v4.44.2>`)

**Comment by WillFP** [comment]
That's intentional behaviour?
