### ISSUE TITLE
Reforge on ecoarmor doesn't work

### ISSUE THREAD

**Issue by nikto0001** [Auxilor/Reforges#16]
Reforge don't go after new versions to put on ecoarmor. In older versions it worked but it doesn't work anymore.

**Server Information**
- Version: 1.18.1 Purpur-1566
- Version of plugin and eco: eco 6.27.0, reforges: 4.47.1, ecoarmor: 7.35.1

**Comment by nikto0001** [comment]
The same applies to ecoitems.....

**Comment by WillFP** [comment]
Add it to target.yml, or update your targets to start with * for each item name, so it allows custom items

**Comment by PrimalPower** [comment]
Whats the syntax for * and what does it do? It's not on the wiki
